### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by vandenman** [juliuspf/Bayesrel#5]
Probably it's a good idea to use `testthat` for automated testing.

e.g., see:

https://testthat.r-lib.org/
http://r-pkgs.had.co.nz/tests.html

**Comment by juliuspfadt** [comment]
So there is not necessarily something wrong with the code? You just suggest to put that functionality in there? And how would a test in that sense look like?

**Comment by vandenman** [comment]
There is not something wrong with the code, but as we make changes it's generally recommended to test if the new changes do not break existing functionality. To create these tests there exists a nice framework called `testthat`.

For example:

Add the directory and test-files like this:
```
--tests/test-bayesianReliability.R
```
and `test-bayesianReliability.R`:
```r
set.seed(123)

test_that("Reliability estimates are correct", {
  
  data(cavalini, package = "Bayesrel")
  ee <- Bayesrel::strel(cavalini, estimates = "lambda2")
  
  expect_equal(
    ee$bay$est$bayes.l2,
    0.784585622470221, 
    tolerance = 1e-4
  )
})
```

An easy way to set up everything is `usethis::use_testthat()`. A feature of github is that it can run all tests automagically on every pull request.

**Comment by juliuspfadt** [comment]
Okay. So how many of these tests would I put in there, and how complicated do those usually have to be? meaning, are they meant to break the package? Do you have some testdata i could use, other than the one you put in the other issue?
